/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


#define GPIOA_BASE  0x40010800
#define RCC_BASE  0x40021000
// enable RCC CLK for the GPIO
#define RCC_APB2ENR *(volatile uint32_t *)(RCC_BASE + 0x18)
// Adjusting the GPIO MODE and Pin
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)


/*
 * professional way
 */
typedef union{
	uint32_t all_fields;
	struct{
		uint32_t reserved:13;
		uint32_t p_13:1;
	}pin_t;
} Ureg_ODR_t;


volatile Ureg_ODR_t* R_ODR = (volatile uint32_t *)(GPIOA_BASE + 0x0C);
volatile uint8_t BSS_var[5] ;
static volatile uint8_t BSS_var[5] ;

int main(void)
{
	RCC_APB2ENR |= 1<<2;
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;

	while(1){
		R_ODR->pin_t.p_13 = 1;
		//GPIOA_ODR &= ~(1<<13);
		for(int i = 0; i < 1000000 ; i++);
		R_ODR->pin_t.p_13 = 0;
		//GPIOA_ODR |= 1<<13; // set bit 13
		for(int i = 0; i < 1000000 ; i++); // set bit 13
	}

}
